Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2019-05, with the labels that each got.

#281 Fix Stack Exchange authentication handler
  src/AspNet.Security.OAuth.StackExchange/StackExchangeAuthenticationHandler.cs
  src/AspNet.Security.OAuth.StackExchange/StackExchangeAuthenticationOptions.cs
Labels: bug

#272 fix BattleNet userinfo endpoint
  src/AspNet.Security.OAuth.BattleNet/BattleNetAuthenticationDefaults.cs
Labels: bug

#293 Update Paypal provider to use OAuth user endpoint
  src/AspNet.Security.OAuth.Paypal/PaypalAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Paypal/PaypalAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Paypal/bundle.json
Labels: enhancement

#299 Add Editor Config file
  .editorconfig
  src/AspNet.Security.OAuth.ArcGIS/ArcGISAuthenticationOptions.cs
  src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationOptions.cs
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Myob/MyobAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Strava/StravaAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Vkontakte/VkontakteAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Weibo/WeiboAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/ApplicationFactory.cs
Labels: enhancement

#262 Increase support for authorization of Wechat Webpage
  src/AspNet.Security.OAuth.Weixin/WeixinAuthenticationHandler.cs
  test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/LoopbackRedirectHandler.cs
  test/AspNet.Security.OAuth.Providers.Tests/Wechat/WechatTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Wechat/bundle.json
Labels: enhancement

#245 Add Baidu provider
  AspNet.Security.OAuth.Providers.sln
  src/AspNet.Security.OAuth.Baidu/AspNet.Security.OAuth.Baidu.csproj
  src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Baidu/BaiduTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Baidu/bundle.json
Labels: enhancement

#180 Add a new provider for www.getharvest.com
  AspNet.Security.OAuth.Providers.sln
  src/AspNet.Security.OAuth.Harvest/AspNet.Security.OAuth.Harvest.csproj
  src/AspNet.Security.OAuth.Harvest/HarvestAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Harvest/HarvestAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Harvest/HarvestAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Harvest/HarvestAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Harvest/HarvestTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Harvest/bundle.json
Labels: enhancement

#298 Fix LinkedIn provider with v2 endpoints to get name, email and profile pictures
  .editorconfig
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationConstants.cs
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationHandler.cs
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/ApplicationFactory.cs
  test/AspNet.Security.OAuth.Providers.Tests/LinkedIn/LinkedInTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/LinkedIn/bundle.json
  test/AspNet.Security.OAuth.Providers.Tests/OAuthTests`1.cs
Labels: enhancement

#303 Use HTTPS links
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: enhancement

#304 Add Zalo provider
  AspNet.Security.OAuth.Providers.sln
  README.md
  src/AspNet.Security.OAuth.Zalo/AspNet.Security.OAuth.Zalo.csproj
  src/AspNet.Security.OAuth.Zalo/ZaloAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Zalo/ZaloAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Zalo/ZaloAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Zalo/ZaloAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Zalo/ZaloTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Zalo/bundle.json
Labels: enhancement, new provider

#308 Simplify AddQueryString() calls
  src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationHandler.cs
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Weibo/WeiboAuthenticationHandler.cs
Labels: enhancement
