Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2019-09, with the labels that each got.

#336 incorrect LoginPath
  samples/Mvc.Client/Startup.cs
Labels: bug

#340 Fix assembly copyrights
  Directory.Build.props
  Directory.Build.targets
Labels: bug

#342 Update to ASP.NET Core 3.0 RC1
  eng/Versions.props
  global.json
Labels: enhancement

#343 Add Sign in with Apple provider
  .gitattributes
  AspNet.Security.OAuth.Providers.sln
  README.md
  eng/Versions.props
  samples/Mvc.Client/Startup.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationEvents.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationOptions.cs
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationOptionsExtensions.cs
  src/AspNet.Security.OAuth.Apple/AppleClientSecretGenerator.cs
  src/AspNet.Security.OAuth.Apple/AppleGenerateClientSecretContext.cs
  src/AspNet.Security.OAuth.Apple/AppleIdTokenValidator.cs
  src/AspNet.Security.OAuth.Apple/AppleKeyStore.cs
  src/AspNet.Security.OAuth.Apple/AppleValidateIdTokenContext.cs
  src/AspNet.Security.OAuth.Apple/AspNet.Security.OAuth.Apple.csproj
  src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs
  src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleIdTokenValidator.cs
  src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleKeyStore.cs
  test/AspNet.Security.OAuth.Providers.Tests/Apple/AppleAuthenticationOptionsTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Apple/AppleClientSecretGeneratorTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Apple/AppleTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Apple/TestKeys.cs
  test/AspNet.Security.OAuth.Providers.Tests/Apple/bundle.json
  test/AspNet.Security.OAuth.Providers.Tests/Apple/test.cer
  test/AspNet.Security.OAuth.Providers.Tests/Apple/test.p8
  test/AspNet.Security.OAuth.Providers.Tests/Apple/test.pfx
  test/AspNet.Security.OAuth.Providers.Tests/AspNet.Security.OAuth.Providers.Tests.csproj
  test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/LoopbackRedirectHandler.cs
  test/AspNet.Security.OAuth.Providers.Tests/OAuthTests`1.cs
Labels: enhancement, new provider

#325 Add Nextcloud provider and unit test
  AspNet.Security.OAuth.Providers.sln
  README.md
  src/AspNet.Security.OAuth.Nextcloud/AspNet.Security.OAuth.Nextcloud.csproj
  src/AspNet.Security.OAuth.Nextcloud/NextcloudAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Nextcloud/NextcloudAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Nextcloud/NextcloudAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Nextcloud/NextcloudAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Nextcloud/NextcloudAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Nextcloud/NextcloudTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Nextcloud/bundle.json
Labels: new provider
