Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2020-05, with the labels that each got.

#420 Add Client-ID header for Helix Twitch API Endpoints
  src/AspNet.Security.OAuth.Twitch/TwitchAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Twitch/TwitchAuthenticationHandler.cs
Labels: important

#425 Fix exception if user cancels Sign in with Apple
  src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs
Labels: bug

#427 Migrated Discord endpoints to new domain
  README.md
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationDefaults.cs
  test/AspNet.Security.OAuth.Providers.Tests/Discord/bundle.json
Labels: important

#415 Discord feature 367 prompt field
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Discord/DiscordTests.cs
Labels: enhancement
