Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2020-02, with the labels that each got.

#366 Expanded discord claims to include avatars and discriminators
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Discord/DiscordTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Discord/bundle.json
Labels: enhancement

#373 Deezer
  AspNet.Security.OAuth.Providers.sln
  README.md
  src/AspNet.Security.OAuth.Deezer/AspNet.Security.OAuth.Deezer.csproj
  src/AspNet.Security.OAuth.Deezer/DeezerAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Deezer/DeezerAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Deezer/DeezerAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Deezer/DeezerAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Deezer/DeezerAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Deezer/DeezerTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Deezer/bundle.json
Labels: new provider

#378 Add Gitee provider
  AspNet.Security.OAuth.Providers.sln
  README.md
  src/AspNet.Security.OAuth.Gitee/AspNet.Security.OAuth.Gitee.csproj
  src/AspNet.Security.OAuth.Gitee/GiteeAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Gitee/GiteeAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Gitee/GiteeAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Gitee/GiteeAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Gitee/GiteeAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Gitee/GiteeTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Gitee/bundle.json
Labels: new provider

#382 Fix log message when Apple ID token validation fails
  src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleIdTokenValidator.cs
Labels: bug, enhancement

#386 Update Reference Assemblies
  Directory.Build.props
Labels: enhancement
