Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2020-10, with the labels that each got.

#481 Handle user cancelling LinkedIn sign in
  src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationHandler.cs
Labels: bug, enhancement

#479 Kloudless provider
  AspNet.Security.OAuth.Providers.sln
  README.md
  docs/README.md
  docs/kloudless.md
  src/AspNet.Security.OAuth.Kloudless/AspNet.Security.OAuth.Kloudless.csproj
  src/AspNet.Security.OAuth.Kloudless/KloudlessAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Kloudless/KloudlessAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Kloudless/KloudlessAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.Kloudless/KloudlessAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Kloudless/KloudlessAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Kloudless/KloudlessTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Kloudless/bundle.json
Labels: new provider

#490 Update staging subdomain
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationOptions.cs
Labels: bug

#488 Email is a mandatory claim in yahoo.
  src/AspNet.Security.OAuth.Yahoo/YahooAuthenticationOptions.cs
Labels: enhancement

#491 Add email to Yahoo tests
  test/AspNet.Security.OAuth.Providers.Tests/Yahoo/YahooTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Yahoo/bundle.json
Labels: enhancement

#493 Add KakaoTalk provider
  AspNet.Security.OAuth.Providers.sln
  README.md
  src/AspNet.Security.OAuth.KakaoTalk/AspNet.Security.OAuth.KakaoTalk.csproj
  src/AspNet.Security.OAuth.KakaoTalk/KakaoTalkAuthenticationConstants.cs
  src/AspNet.Security.OAuth.KakaoTalk/KakaoTalkAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.KakaoTalk/KakaoTalkAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.KakaoTalk/KakaoTalkAuthenticationHandler.cs
  src/AspNet.Security.OAuth.KakaoTalk/KakaoTalkAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/KakaoTalk/KakaoTalkTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/KakaoTalk/bundle.json
Labels: new provider
