Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2020-07, with the labels that each got.

#445 Make loopback handler more flexible
  test/AspNet.Security.OAuth.Providers.Tests/AspNet.Security.OAuth.Providers.Tests.csproj
  test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/LoopbackRedirectHandler.cs
  test/AspNet.Security.OAuth.Providers.Tests/OAuthTests`1.cs
  test/AspNet.Security.OAuth.Providers.Tests/Shopify/ShopifyLoopbackRedirectHandler.cs
  test/AspNet.Security.OAuth.Providers.Tests/Shopify/ShopifyTests.cs
Labels: enhancement

#423 Add GitHub Actions CI
  .github/workflows/build.yml
  .travis.yml
  AspNet.Security.OAuth.Providers.sln
  Directory.Build.props
  README.md
  appveyor.yml
Labels: enhancement

#447 Only push packages from aspnet-contrib
  .github/workflows/build.yml
Labels: enhancement

#446 Update to the Patreon v2 API
  src/AspNet.Security.OAuth.Patreon/PatreonAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Patreon/PatreonAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Patreon/PatreonAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Patreon/PatreonTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Patreon/bundle.json
Labels: enhancement

#448 Move build Id logic to workflow
  .github/workflows/build.yml
  Directory.Build.props
Labels: enhancement

#449 Set DotNetPublishUsingPipelines to true and remove the workaround from Directory.Build.props
  .github/workflows/build.yml
  Directory.Build.props
Labels: enhancement

#452 Always publish logs and test results
  .github/workflows/build.yml
Labels: enhancement

#417 Add SuperOffice provider
  AspNet.Security.OAuth.Providers.sln
  Directory.Packages.props
  README.md
  src/AspNet.Security.OAuth.SuperOffice/AspNet.Security.OAuth.SuperOffice.csproj
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationConstants.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationEnvironment.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationHandler.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationOptions.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationPostConfigureOptions.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeFunctionalRightsClaimAction.cs
  test/AspNet.Security.OAuth.Providers.Tests/Apple/AppleTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/SuperOffice/SuperOfficeTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/SuperOffice/bundle.json
Labels: new provider

#453 Workflow fixes
  .github/workflows/build.yml
Labels: bug, enhancement

#455 Show prerelease versions for MyGet
  README.md
Labels: enhancement

#460 Provider documentation
  README.md
  docs/README.md
  docs/amazon.md
  docs/battlenet.md
  docs/bitbucket.md
  docs/discord.md
  docs/eveonline.md
  docs/foursquare.md
  docs/gitee.md
  docs/github.md
  docs/instagram.md
  docs/linkedin.md
  docs/odnoklassniki.md
  docs/okta.md
  docs/patreon.md
  docs/qq.md
  docs/reddit.md
  docs/salesforce.md
  docs/sign-in-with-apple.md
  docs/stackexchange.md
  docs/superoffice.md
  docs/trakt.md
  docs/twitch.md
  docs/vkontakte.md
  docs/weibo.md
  src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs
  src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationOptions.cs
  src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationOptions.cs
  src/AspNet.Security.OAuth.QQ/QQAuthenticationOptions.cs
  src/AspNet.Security.OAuth.Reddit/RedditAuthenticationOptions.cs
  src/AspNet.Security.OAuth.SuperOffice/SuperOfficeAuthenticationOptions.cs
  src/AspNet.Security.OAuth.Twitch/TwitchAuthenticationOptions.cs
Labels: enhancement

#462 Fix analyzer warnings
  test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/ApplicationFactory.cs
  test/AspNet.Security.OAuth.Providers.Tests/LinkedIn/LinkedInTests.cs
Labels: enhancement

#461 Update to Instagram Basic Display API
  docs/instagram.md
  src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationConstants.cs
  src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Instagram/InstagramTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Instagram/bundle.json
Labels: enhancement
