Repository aspnet-contrib/AspNet.Security.OAuth.Providers, pull requests merged in 2021-07, with the labels that each got.

#573 Implement Adobe IO provider
  AspNet.Security.OAuth.Providers.sln
  README.md
  src/AspNet.Security.OAuth.AdobeIO/AdobeIOAuthenticationConstants.cs
  src/AspNet.Security.OAuth.AdobeIO/AdobeIOAuthenticationDefaults.cs
  src/AspNet.Security.OAuth.AdobeIO/AdobeIOAuthenticationExtensions.cs
  src/AspNet.Security.OAuth.AdobeIO/AdobeIOAuthenticationHandler.cs
  src/AspNet.Security.OAuth.AdobeIO/AdobeIOAuthenticationOptions.cs
  src/AspNet.Security.OAuth.AdobeIO/AspNet.Security.OAuth.AdobeIO.csproj
  test/AspNet.Security.OAuth.Providers.Tests/AdobeIO/AdobeIOTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/AdobeIO/bundle.json
Labels: new provider

#582 Improvement for LINE provider
  src/AspNet.Security.OAuth.Line/LineAuthenticationHandler.cs
Labels: bug

#579 Add support for Dropbox response_type and token_access_type params
  AspNet.Security.OAuth.Providers.sln
  docs/dropbox.md
  src/AspNet.Security.OAuth.Dropbox/DropboxAuthenticationHandler.cs
  src/AspNet.Security.OAuth.Dropbox/DropboxAuthenticationOptions.cs
  test/AspNet.Security.OAuth.Providers.Tests/Dropbox/DropboxTests.cs
  test/AspNet.Security.OAuth.Providers.Tests/Dropbox/bundle.json
Labels: enhancement
